### ISSUE TITLE
Shortcuts for non-SDK components

### ISSUE THREAD

**Issue by paulvi** [pellaton/eclipse-cheatsheet#8]
What is your idea on how to approach shortcuts for non-SDK components like HTML Editor, SQL, remote/local Terminal ?

**Comment by pellaton** [comment]
The cheat sheets as they are made available here cover the traditional Eclipse SDK package.
Due to the modularity of Eclipse and the growing number of different packages there are two possibilities
a) provide a separate cheat sheet for every package
b) provide a cheat sheet with all shortcuts of all available packages and plugins
c) generate the cheat sheet using code instead of manually (as now)

a) and b) are both not very practical. c) would be great but this would be something completely new and should be handled in a different project.
